# Generated by Django 3.2.9 on 2021-11-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('SellDateTime', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Lessonscore',
        ),
        migrations.AddField(
            model_name='productsell',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.product', verbose_name='product'),
        ),
    ]
